base:
  project: Fantacy Sports
  team: Sinister 6

data:
  web_scrapper_output: output
  batting_file: "data/batting_data.csv"
  bowling_file: "data/bowling_data.csv"
  fielding_file: "data/fielding_data.csv"
  output_file: "data/recent_player_form.csv"
  overall_performance: "data/overall.csv"
  squad_file: "data/squad.csv"
  player_form: "data/recent_player_form.csv"
  squad_input: "data/SquadPlayerNames.csv"
  previous_months: 20
  decay_rate: 0.1
  competition:
    output: "sinister6.csv"

algorithm:
  batter_weight: 1.0
  bowler_weight: 1.0
  allrounder_weight: 1.15
  keeper_weight: 1.0
  overall_performance: 0.4
  recent_player_form: 0.6

ga:
  population_size: 50
  generations: 100
  tournament_size: 3
  mutation_rate: 0.1
