base:
  project: Fantacy Sports
  team: Sinister 6

data:
  web_scrapper_output: output
  batting_file: "data/batting_data.csv"
  bowling_file: "data/bowling_data.csv"
  fielding_file: "data/fielding_data.csv"
  output_file: "data/recent_player_form.csv"
  squad_file: "data/squad.csv"
  player_form: "data/recent_player_form.csv"
  squad_input: "Downloads/SquadPlayerNames.csv"
  previous_months: 20
  decay_rate: 0.1

algorithm:
  batter_weight: 1.0
  bowler_weight: 1.0
  allrounder_weight: 1.0
  keeper_weight: 1.0

# champions_trophy_2025_teams
teams:
  - Bangladesh
  - India
  - New Zealand
  - Pakistan
  - Australia
  - England
  - South Africa
  - Afghanistan


# champions_trophy_2025_squads
squad:
  Bangladesh:
    - Jaker Ali Anik                # Jaker Ali Anik (wk)
    - Mehidy Hasan Miraz            # Mehidy Hasan Miraz
    - Mahmudullah                   # Mohammad Mahmudullah
    - Mohammad Parvez Hossain-Emon  # Mohammad Parvez Hossain-Emon
    - Mushfiqur Rahim               # Mushfiqur Rahim (wk)
    - Mustafizur Rahman             # Mustafizur Rahman
    - Nahid Rana                    # Nahid Rana
    - Najmul Hossain Shanto         # Najmul Hossain Shanto (c)
    - Nasum Ahmed                   # Nasum Ahmed
    - Rishad Hossain                # Rishad- Hossain
    - Soumya Sarkar                 # Soumya Sarkar
    - Tanzid Hasan                  # Tanzid Hasan
    - Tanzim Hasan Sakib            # Tanzim Sakib
    - Taskin Ahmed                  # Taskin Ahmed
    - Towhid Hridoy                 # Tawhid Hridoy

  India:
    - Arshdeep Singh           # Arshdeep Singh
    - AR Patel                 # Axar Patel
    - HH Pandya                # Hardik Pandya
    - Harshit Rana             # Harshit Rana
    - Kuldeep Yadav            # Kuldeep Yadav
    - KL Rahul                 # Lokesh Rahul (wk)
    - Mohammed Shami           # Mohammed Shami
    - RA Jadeja                # Ravindra Jadeja
    - RR Pant                  # Rishabh Pant (wk)
    - RG Sharma                # Rohit Sharma (c)
    - SS Iyer                  # Shreyas Iyer
    - Shubman Gill             # Shubman Gill (vc)
    - Varun Chakravarthy       # Varun Chakravarthy
    - V Kohli                  # Virat Kohli
    - Washington Sundar        # Washington Sundar

  New Zealand:
    - DJ Mitchell              # Daryl Mitchell
    - DP Conway                # Devon Conway (wk)
    - GD Phillips              # Glenn Phillips
    - JA Duffy                 # Jacob Duffy
    - KS Williamson            # Kane Williamson
    - KA Jamieson              # Kyle Jamieson
    - MS Chapman               # Mark Chapman
    - MJ Henry                 # Matt Henry
    - MG Bracewell             # Michael Bracewell
    - MJ Santner               # Mitchell Santner (c)
    - NG Smith                 # Nathan Smith
    - R Ravindra               # Rachin Ravindra
    - TWM Latham               # Tom Latham (wk)
    - WA Young                 # Will Young
    - W O'Rourke               # William O'Rourke

  Pakistan:
    - Abrar Ahmed              # Abrar Ahmed
    - Agha Salman              # Salman Ali Agha (vc)
    - Babar Azam               # Babar Azam
    - Faheem Ashraf            # Faheem Ashraf
    - Fakhar Zaman             # Fakhar Zaman
    - Haris Rauf               # Haris Rauf
    - Kamran Ghulam            # Kamran Ghulam
    - Khushdil Shah            # Khushdil Shah
    - Mohammad Hasnain         # Mohammad Hasnain
    - Mohammad Rizwan          # Mohammad Rizwan (c, wk)
    - Naseem Shah              # Naseem Shah
    - Saud Shakeel             # Saud Shakeel
    - Shaheen Shah Afridi      # Shaheen Afridi
    - Tayyab Tahir             # Tayyab Tahir
    - Usman Khan               # Usman Khan

  Australia:
    - AM Hardie                # Aaron Hardie
    - A Zampa                  # Adam Zampa
    - AT Carey                 # Alex Carey (wk)
    - BJ Dwarshuis             # Ben Dwarshuis
    - C Connolly               # Cooper Connolly
    - GJ Maxwell               # Glenn Maxwell
    - JF-MacGurk               # Jake Fraser-McGurk
    - JP Inglis                # Josh Inglis(wc)
    - M Labuschagne            # Marnus Labuschagne
    - MW Short                 # Matthew Short
    - NT Ellis                 # Nathan Ellis
    - SA Abbott                # Sean Abbott
    - SH Johnson               # Spencer Johnson
    - T Sangha                 # Tanveer Sangha
    - TM Head                  # Travis Head
    - SPD Smith                # Steven Smith (C)

  England:
    - AU Rashid                # Adil Rashid
    - BM Duckett               # Ben Duckett
    - BA Carse                 # Brydon Carse
    - AAP Atkinson             # Gus Atkinson
    - HC Brook                 # Harry Brook
    - J Overton                # Jamie Overton
    - JL Smith                 # Jamie Smith
    - JE Root                  # Joe Root
    - JC Archer                # Jofra Archer
    - JC Buttler               # Jos Buttler (c, wk)
    - LS Livingstone           # Liam Livingstone
    - MA Wood                  # Mark Wood
    - PD Salt                  # Philip Salt (wk)
    - S Mahmood                # Saqib Mahmood
    - T Banton                 # Tom Banton

  South Africa:
    - AK Markram               # Aiden Markram
    - C Bosch                  # Corbin Bosch
    - DA Miller                # David Miller
    - H Klaasen                # Heinrich Klaasen (wk)
    - K Rabada                 # Kagiso Rabada
    - KA Maharaj               # Keshav Maharaj
    - L Ngidi                  # Lungi Ngidi
    - M Jansen                 # Marco Jansen
    - HE van der Dussen        # Rassie van der-Dussen
    - RD Rickleton             # Ryan Rickelton (wicketkeeper)
    - T Shamsi                 # Tabraiz Shamsi
    - T Bavuma                 # Temba Bavuma (c)
    - T de Zorzi               # Tony de Zorzi
    - T Stubbs                 # Tristan Stubbs
    - PWA Mulder               # Wiaan Mulder

  Afghanistan:
    - Azmatullah Omarzai       # Azmatullah Omarzai
    - Bilal Sami               # Bilal Sami
    - Darwish Rasooli          # Darwish Rasooli
    - Fareed Ahmed Malik       # Fareed Ahmed Malik
    - Fazalhaq Farooqi         # FazalHaq Farooqi
    - Gulbadin Naib            # Gulbadin Naib
    - Hashmatullah Shahidi     # Hashmatullah Shahidi (c)
    - Ibrahim Zadran           # Ibrahim Zadran
    - Ikram Alikhil            # Ikram Alikhil (wicketkeeper)
    - Mohammad Nabi            # Mohammad Nabi
    - Nangeyalia Kharote       # Nangeyalia Kharote
    - Naveed Zadran            # Naveed Zadran
    - Noor Ahmad               # Noor Ahmad
    - Rahmanullah Gurbaz       # Rahmanullah Gurbaz (wk)
    - Rahmat Shah              # Rahmat Shah
    - Rashid Khan              # Rashid-Khan
    - Sediqullah Atal          # Sediqullah Atal
